### ISSUE TITLE
Request: support for the mod "Making Friends"

### ISSUE THREAD

**Issue by Seinra** [YLMstring/Mythic-Magic-Mayhem#1]
This mod is having some issues to work alongside "Making Friends", when you have to pick your first mythic spells, the game force you to pick spells from lvl 3 and 7 instead of lvl 1.

Making Friends: https://github.com/Balkoth-dev/WOTR_MAKING_FRIENDS

**Comment by YLMstring** [comment]
what do ya mean? summoner is not a full caster so can not merge in the first place?

**Comment by Seinra** [comment]
Yes, it was a surprise for me too haha.
It turns out that I installed the mod by quickly reading "what it does" and didn't notice the part about it being only for "full casters". So, under the idea that I was going to be able to merge the aeon/summoner spellbooks, I created a new character in the DLC, and when I leveled up the character until I got the "mythic spellbook", I noticed that I can't merge the spellbooks (now I know why) and the bug: the first spells that I was given to learn from Aeon were from caster level 3 and 7 instead of cl 1.
I don't know how, but your mod is touching the Summoner mod without having to merge the spellbooks.

**Comment by YLMstring** [comment]
only summoner gets level 3 and 7, while other characters gain cl 1?

**Comment by Seinra** [comment]
> only summoner gets level 3 and 7, while other characters gain cl 1?

Yes, only the Summoner has the problem, I created an Endritch Scion to test it and it learns the right spells for its mythic level without issues.

**Comment by YLMstring** [comment]
Fixed in 0.2.0!
