### ISSUE TITLE
Thassilonian Specialist doesn't have merge option

### ISSUE THREAD

**Issue by abishai** [YLMstring/Mythic-Magic-Mayhem#14]
Merge Spellbook option is not available for Thassilotian Specialists for some reason.
I've tried Lust+Demon combination, but probably it doesn't matter. Is it RAW feature or a bug?

**Comment by abishai** [comment]
Looks similar to https://github.com/YLMstring/Mythic-Magic-Mayhem/issues/10
I'll start a new game with Thassilotian Specialist PC in hope it will be eventually fixed ><

**Comment by YLMstring** [comment]
should fix in 1.1.4!
