### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Seinra** [YLMstring/Mythic-Magic-Mayhem#3]
When using the mod Spellbook Merge, once you "merge" the mythic spellbook with a normal spellbook, each time you level up your mythic class the spells you are able to learn are all from your "normal spellbook". Example: when you merge the Angel's spellbook with an Wizard's spellbook, each time you level up the Angel class, the spells you can learn are all from the Wizard's spellbook.

Request: toggeable to be able to learn spells from the mythic class instead of the normal class when you level up your mythic class and the spellbooks are merged.

Why?

1) If you have two classes that level up in different instances, the spells you can learn should be split into instances as well for each class, allowing you to learn EVERYTHING each class has to offer instead of being forced to pick spells from only one class.
2) In the vanilla spellbook merge configuration (without mods), the spellbooks from Mythic classes have the same selection of "normal" spells as the spellbooks from normal classes, allowing them to choose without "cons" their spells.

**Comment by YLMstring** [comment]
MMM spellbook merge should behave like vanilla because I basically disable Spellbook Merge Mod's stuff lol

**Comment by Seinra** [comment]
> MMM spellbook merge should behave like vanilla because I basically disable Spellbook Merge Mod's stuff lol

I know, the feature I was requesting is a toggeable option in your mod that would allow a Wizard (or any other full arcane caster) to learn the Angel spells (divine) when leveling up Angel and the spellbooks are merged. Same with a Cleric (or any other divine full caster) merging spellbooks with a Lich, to make this class be able to learn the Lich spells (arcane) when leveling up the Lich mythic class.

**Comment by YLMstring** [comment]
I don't understand, aren't mythic spells automatically learned at the specified mythic level?

**Comment by Seinra** [comment]
> I don't understand, aren't mythic spells automatically learned at the specified mythic level?

The "mythic" spells yes, the "normal" spells from the Mythic spellbook are not.
Besides the "mythic spells", Lich and Wizard have almost the same selection of "normal" spells, if you merge their spellbooks, you won't notice big differences at learning new spells when you level up your Lich, but this is different if you merge Wizard with Angel, in the same situation you are FORCED to learn the normal Wizard spells when leveling up Angel, yet you still get the automatic Mythic Angel spells.

Wizard-Angel merged spellbooks:
![image](https://github.com/YLMstring/Mythic-Magic-Mayhem/assets/7744272/0cbf8900-c58e-40ff-8882-94de66381b3a)

Wizard-Angel no merged spelbooks:
![image](https://github.com/YLMstring/Mythic-Magic-Mayhem/assets/7744272/f42fe483-9b09-43c7-9505-9e90d13eeac8)

Wizard-Lich merged spellbooks:
![image](https://github.com/YLMstring/Mythic-Magic-Mayhem/assets/7744272/ece0c183-4d1a-4d2a-8f47-7fa5ada55492)

Wizard-Lich no merged spelbooks:
![image](https://github.com/YLMstring/Mythic-Magic-Mayhem/assets/7744272/7411feb7-a347-4092-9f2a-aae05464fce4)

**Comment by YLMstring** [comment]
sounds op to me

**Comment by Seinra** [comment]
> sounds op to me

Well, if you think that I'll have to stay with the spellbooks split hahaha.
