### ISSUE TITLE
Request: Support for the mod "Path of Bling"

### ISSUE THREAD

**Issue by Seinra** [YLMstring/Mythic-Magic-Mayhem#4]
Hello! Another support request.

This time for the mod Path of Bling https://github.com/Balkoth-dev/WOTR_PATH_OF_BLING, this mod adds a spontaneous caster spellbook to the Dragon mythic path.

**Comment by YLMstring** [comment]
but it's not a mythic spell book I assume? there's no mythic spells in the book

**Comment by Seinra** [comment]
> but it's not a mythic spell book I assume? there's no mythic spells in the book

Yep, the spells are not mythic, but when you choose Gold Dragon, your spellbooks split as if you hadn't merged them.

**Comment by YLMstring** [comment]
What would be happening to vanilla merged book?

**Comment by Seinra** [comment]
> What would be happening to vanilla merged book?

I don't understand your question... For me vanilla means "without mods".

**Comment by YLMstring** [comment]
Yep, I mean does path of bling break vanilla angel-oracle/lich-wizard merge?

**Comment by Seinra** [comment]
> Yep, I mean does path of bling break vanilla angel-oracle/lich-wizard merge?

Yep, I tested it and the spelbooks get split in vanilla, one for your main class with all the spells you already learned (mythic spells too) and a another spellbook with the Gold Dragon spells(Path of Bling) only.

**Comment by YLMstring** [comment]
It's his bug to fix then, muahahaha
